### ISSUE TITLE
`ember.debug.js` should be used in development

### ISSUE THREAD

**Issue by alex88** [tricknotes/ember-middleman#3]
Hi, while running in development is possible to automatically include `ember.debug.js` instead of `ember.js` as stated by the library?

**Comment by tricknotes** [comment]
> while running in development shouldn't be better to use `ember.debug.js` instead of `ember.js` as stated by the library?

You're right.
Additionally, `ember.prod.js` should be  used when running `middleman build` in automatically.
But it is not supported yet.

> Also using your gem (instead of `middleman-ember`, which doesn't work due other issues) the chrome inspector for ember doesn't work, have you tried it, know what could be the cause?

It works for me.
Could you provide example code or stack trace?

**Comment by alex88** [comment]
@tricknotes about the inspector, after a reset of the project it worked fine, that's why I removed it from the comment, thanks ;)

**Comment by tricknotes** [comment]
It's OK.

I updated PR title targeted `ember.debug.js` issue :)
